server:
  port: 8000
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/milk_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root